import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';
import HomePage from '../components/pages/Homepage';
import client from '../lib/apolloClient';
import { HOMEPAGE } from '../lib/queries';

export default function Home({ homepageData }) {
	return (
		<>
			<Head>
				<title>Ao Vua</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout home={true}>
				<HomePage homepageData={homepageData} />
			</Layout>
		</>
	);
}

export async function getStaticProps() {
	// graphQL query
	const { data } = await client.query({
		query: HOMEPAGE,
	});
	return {
		props: {
			homepageData: data.homepage,
		},
	};
}
