import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';
import HomePage from '../components/pages/Homepage';
import client from '../lib/apolloClient';
import { HOMEPAGE, LATEST_NEWS } from '../lib/queries';

export default function Home({ homepageData, articles }) {
	return (
		<>
			<Head>
				<title>Ao Vua</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout home={true}>
				<HomePage homepageData={homepageData} articles={articles} />
			</Layout>
		</>
	);
}

export const getStaticProps = async () => {

	const homepageQuery = client.query({
		query: HOMEPAGE,
	});

	const latestNewsQuery = client.query({
		query: LATEST_NEWS,
	});

	const responses = await Promise.all([homepageQuery, latestNewsQuery]);

	return {
		props: {
			homepageData: responses[0].data.homepage,
			articles: responses[1].data.articles,
		},
	};
};
