import React from 'react';
import Head from 'next/head';
import PageTitle from '../../components/main/PageTitle';
import { ARTICLES } from '../../lib/queries/articles';
import client from '../../lib/apolloClient';
import News from '../../components/main/news/News';

const NewsPage = ({ articles }) => {
	return (
		<>
			<Head>
				<title>Tin tức | Ao Vua JSC.</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<PageTitle pageTitle="Tin tức của Ao Vua JSC." breadcrumb={null} />
			<News articles={articles} />
		</>
	);
};

export const getStaticProps = async () => {
	const articlesQuery = await client.query({
		query: ARTICLES,
	});

	return {
		props: {
			articles: articlesQuery.data.articles,
		},
	};
};

export default NewsPage;
