import React from 'react';
import Head from 'next/head';
import PageTitle from '../../components/main/PageTitle';
import { ARTICLES, CATEGORIES } from '../../lib/queries/articles';
import client from '../../lib/apolloClient';
import News from '../../components/main/news/News';
import WithTransition from '../../components/utils/WithTransition';

const NewsPage = ({ articles, categories }) => {
	return (
		<>
			<Head>
				<title>Tin tức | Ao Vua JSC.</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<WithTransition>
				<PageTitle
					pageTitle="Tin tức của Ao Vua JSC."
					breadcrumb={null}
				/>
				<News articles={articles} categories={categories} />
			</WithTransition>
		</>
	);
};

export const getStaticProps = async () => {
	const articlesQuery = client.query({
		query: ARTICLES,
	});
	const categoriesQuery = client.query({
		query: CATEGORIES,
	});

	const responses = await Promise.all([articlesQuery, categoriesQuery]);

	return {
		props: {
			articles: responses[0].data.articles,
			categories: responses[1].data.categories,
		},
	};
};

export default NewsPage;
